# Declare version
version: "3"
services:
  # If you want to retain data, you need to mount directories yourself
  mysql:
    # Specify the image address
    image: cap1573/mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
  # Service name, which can be accessed within the same network
  consul:
    # Specify the image address
    image: cap1573/consul
    ports:
      - "8500:8500"
  # Distributed tracing
  jaeger:
    image: cap1573/jaeger
    ports:
      - "6831:6831/udp"
      - "16686:16686"
  # Monitoring
  prometheus:
    image: cap1573/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  # Monitoring dashboard
  grafana:
    image: cap1573/grafana
    ports:
      - "3000:3000"

  # Circuit breaker
  hystrix-dashboard:
    # Specify the image name
    image: cap1573/hystrix-dashboard
    ports:
      - "9002:9002"
  # ELK stack
  elasticsearch:
    image: cap1573/elasticsearch:7.9.3
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: imoocpwd
      discovery.type: single-node
      network.publish_host: _eth0_
  logstash:
    image: cap1573/logstash:7.9.3
    ports:
      - "5044:5044"
      - "5000:5000"
      - "9600:9600"
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
  kibana:
    image: cap1573/kibana:7.9.3
    ports:
      - "5601:5601"
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    # Added later for optimization, this means wait for elasticsearch to start normally
    depends_on:
      - elasticsearch
