global:
  scrape_interval: 15s 
  external_labels:
    monitor: 'go-micro-imooc-monitor'
scrape_configs:

  - job_name: 'order'
    scrape_interval: 5s 
    static_configs:

      - targets: ['192.168.0.104:9092']