# Declare version
version: "3"
# Define services
services:
  # Service name, can be accessed by name within the same network
  consul:
    # Specify the image address
    image: cap1573/consul
    # Port mapping for the image
    ports:
      - "8500:8500"
  # Service name, can be accessed by name within the same network
  jaeger:
    # Specify the image address
    image: cap1573/jaeger
    # Port mapping for the image
    ports:
      - "6831:6831/udp"
      - "16686:16686"
  # Circuit breaker dashboard
  hystrix-dashboard:
    # Specify the image address
    image: cap1573/hystrix-dashboard
    # Port mapping for the image
    ports:
      - "9002:9002"
  # Monitoring dashboard
  prometheus:
    # Specify the image address
    image: cap1573/prometheus
    # Mount external yml file to the container
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  # Monitoring dashboard
  grafana:
    # Specify the image address
    image: cap1573/grafana
    # Port mapping for the image
    ports:
      - "3000:3000"
